services:
  # nginx:
  #   image: nginx:1
  #   environment:
  #     TZ: Asia/Seoul
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./certbot/conf:/etc/letsencrypt
  #   restart: always
  certbot:
    image: certbot/certbot
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do echo manual; sleep 12h & wait $${!}; done;'"