services:
  nginx:
    image: nginx:1
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
    restart: always
  certbot:
    image: certbot/dns-cloudflare
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/entrypoint.sh:/etc/letsencrypt/entrypoint.sh
      - ./certbot/cloudflare.ini:/etc/letsencrypt/cloudflare.ini
    entrypoint: "sh /etc/letsencrypt/entrypoint.sh"