services:
  nginx:
    image: nginx:1
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
  certbot:
    image: certbot/certbot
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "certbot certonly --webroot --webroot-path /var/www/certbot --email email@domain.com --agree-tos --no-eff-email -d domain.com -d *.domain.com"